# @package _group_
model:
  _target_: mbrl.models.ValueWeightedModel
  device: ${device}
  num_layers: 4
  in_size: ???
  out_size: ???
  ensemble_size: 7
  hid_size: 200
  use_silu: true
  use_scaling: true
  use_vaml: false
  add_mse: false
  bound_clipping: true
  bound_clipping_quantile: 0.95
  use_all_vf: true
  propagation_method: random_model
